<?php
			if( function_exists('acf_add_local_field_group') ):

                acf_add_local_field_group(array(
                    'key' => 'group_641310fd32885',
                    'title' => 'تیم ولکام دوبی',
                    'fields' => array(
                        array(
                            'key' => 'field_641310fdf37a9',
                            'label' => 'تیم ولکام دوبی',
                            'name' => 'ours',
                            'aria-label' => '',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'table',
                            'pagination' => 0,
                            'min' => 0,
                            'max' => 0,
                            'collapsed' => '',
                            'button_label' => 'سطر جدید',
                            'rows_per_page' => 20,
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_64131116f37aa',
                                    'label' => 'آواتار',
                                    'name' => 'avatar',
                                    'aria-label' => '',
                                    'type' => 'image',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'return_format' => 'url',
                                    'library' => 'all',
                                    'min_width' => '',
                                    'min_height' => '',
                                    'min_size' => '',
                                    'max_width' => '',
                                    'max_height' => '',
                                    'max_size' => '',
                                    'mime_types' => '',
                                    'preview_size' => 'medium',
                                    'parent_repeater' => 'field_641310fdf37a9',
                                ),
                                array(
                                    'key' => 'field_6413112ff37ab',
                                    'label' => 'نام',
                                    'name' => 'name',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'parent_repeater' => 'field_641310fdf37a9',
                                ),
                                array(
                                    'key' => 'field_64131136f37ac',
                                    'label' => 'سمت',
                                    'name' => 'semat',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'parent_repeater' => 'field_641310fdf37a9',
                                ),
                            ),
                        ),
                    ),
                    'location' => array(
                        array(
                            array(
                                'param' => 'page_template',
                                'operator' => '==',
                                'value' => 'about.php',
                            ),
                        ),
                    ),
                    'menu_order' => 0,
                    'position' => 'normal',
                    'style' => 'default',
                    'label_placement' => 'top',
                    'instruction_placement' => 'label',
                    'hide_on_screen' => '',
                    'active' => true,
                    'description' => '',
                    'show_in_rest' => 0,
                ));
                
                acf_add_local_field_group(array(
                    'key' => 'group_641316cb021c6',
                    'title' => 'خانه ها',
                    'fields' => array(
                        array(
                            'key' => 'field_641316cbca02e',
                            'label' => 'خانه ها',
                            'name' => 'houses',
                            'aria-label' => '',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'block',
                            'pagination' => 0,
                            'min' => 0,
                            'max' => 0,
                            'collapsed' => '',
                            'button_label' => 'سطر جدید',
                            'rows_per_page' => 20,
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_641316e4ca02f',
                                    'label' => 'تصاویر',
                                    'name' => 'pics',
                                    'aria-label' => '',
                                    'type' => 'gallery',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'return_format' => 'url',
                                    'library' => 'all',
                                    'min' => '',
                                    'max' => '',
                                    'min_width' => '',
                                    'min_height' => '',
                                    'min_size' => '',
                                    'max_width' => '',
                                    'max_height' => '',
                                    'max_size' => '',
                                    'mime_types' => '',
                                    'insert' => 'append',
                                    'preview_size' => 'medium',
                                    'parent_repeater' => 'field_641316cbca02e',
                                ),
                                array(
                                    'key' => 'field_641316feca030',
                                    'label' => 'عنوان خانه',
                                    'name' => 'title',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'parent_repeater' => 'field_641316cbca02e',
                                ),
                                array(
                                    'key' => 'field_6413170cca031',
                                    'label' => 'مکان',
                                    'name' => 'place',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'parent_repeater' => 'field_641316cbca02e',
                                ),
                                array(
                                    'key' => 'field_6413171dca032',
                                    'label' => 'امکانات',
                                    'name' => 'feau',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'parent_repeater' => 'field_641316cbca02e',
                                ),
                                array(
                                    'key' => 'field_6413172aca033',
                                    'label' => 'شروع قیمت',
                                    'name' => 'price',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'parent_repeater' => 'field_641316cbca02e',
                                ),
                            ),
                        ),
                    ),
                    'location' => array(
                        array(
                            array(
                                'param' => 'page_template',
                                'operator' => '==',
                                'value' => 'khane.php',
                            ),
                        ),
                    ),
                    'menu_order' => 0,
                    'position' => 'normal',
                    'style' => 'default',
                    'label_placement' => 'top',
                    'instruction_placement' => 'label',
                    'hide_on_screen' => '',
                    'active' => true,
                    'description' => '',
                    'show_in_rest' => 0,
                ));
                
                acf_add_local_field_group(array(
                    'key' => 'group_64130cd0591a7',
                    'title' => 'سوالات متداول',
                    'fields' => array(
                        array(
                            'key' => 'field_64130cd586a50',
                            'label' => 'سوالات متداول',
                            'name' => 'faqs',
                            'aria-label' => '',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'table',
                            'pagination' => 0,
                            'min' => 0,
                            'max' => 0,
                            'collapsed' => '',
                            'button_label' => 'سطر جدید',
                            'rows_per_page' => 20,
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_64130d2686a51',
                                    'label' => 'عنوان',
                                    'name' => 'title',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'parent_repeater' => 'field_64130cd586a50',
                                ),
                                array(
                                    'key' => 'field_64130d2f86a52',
                                    'label' => 'پاسخ سوال',
                                    'name' => 'text',
                                    'aria-label' => '',
                                    'type' => 'textarea',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'rows' => '',
                                    'placeholder' => '',
                                    'new_lines' => '',
                                    'parent_repeater' => 'field_64130cd586a50',
                                ),
                            ),
                        ),
                    ),
                    'location' => array(
                        array(
                            array(
                                'param' => 'page_template',
                                'operator' => '==',
                                'value' => 'index.php',
                            ),
                        ),
                        array(
                            array(
                                'param' => 'page_template',
                                'operator' => '==',
                                'value' => 'car.php',
                            ),
                        ),
                        array(
                            array(
                                'param' => 'page_template',
                                'operator' => '==',
                                'value' => 'khane.php',
                            ),
                        ),
                    ),
                    'menu_order' => 0,
                    'position' => 'normal',
                    'style' => 'default',
                    'label_placement' => 'top',
                    'instruction_placement' => 'label',
                    'hide_on_screen' => '',
                    'active' => true,
                    'description' => '',
                    'show_in_rest' => 0,
                ));
                
                acf_add_local_field_group(array(
                    'key' => 'group_64130ba8ea4fe',
                    'title' => 'صفحه اصلی',
                    'fields' => array(
                        array(
                            'key' => 'field_64130ba958f10',
                            'label' => 'لینک صفحه خدمات',
                            'name' => 'services',
                            'aria-label' => '',
                            'type' => 'page_link',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'post_type' => array(
                                0 => 'page',
                            ),
                            'taxonomy' => '',
                            'allow_archives' => 1,
                            'multiple' => 0,
                            'allow_null' => 0,
                        ),
                        array(
                            'key' => 'field_64130e3e38fed',
                            'label' => 'لینک صفحه تماس باما',
                            'name' => 'contact_us',
                            'aria-label' => '',
                            'type' => 'page_link',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'post_type' => array(
                                0 => 'page',
                            ),
                            'taxonomy' => '',
                            'allow_archives' => 1,
                            'multiple' => 0,
                            'allow_null' => 0,
                        ),
                        array(
                            'key' => 'field_64130bfd2e5bd',
                            'label' => 'متن درباره ی شرکت',
                            'name' => 'about',
                            'aria-label' => '',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 'هلدینگ «ولکام دبی» از سال 2005 فعالیت خود را در دبی آغاز کرده است. فعالیت این مجموعه هم در ایران و هم در دبی کاملاً قانونی است. دفاتر معتبر این هلدینگ در تهران و دبی همواره آمادۀ پاسخگویی و ارائۀ مشاوره دربارۀ خدمات و فعالیت‌های این مجموعه هستند. مدیران و کارمندان این مجموعه نیز از افراد قدیمی این حوزه هستند و بیش از بیست سال است که در دبی مشغول به فعالیت هستند.',
                            'maxlength' => '',
                            'rows' => '',
                            'placeholder' => '',
                            'new_lines' => '',
                        ),
                        array(
                            'key' => 'field_64130c112e5be',
                            'label' => 'صفحه ی درباره ی ما',
                            'name' => 'about_url',
                            'aria-label' => '',
                            'type' => 'page_link',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'post_type' => array(
                                0 => 'page',
                            ),
                            'taxonomy' => '',
                            'allow_archives' => 1,
                            'multiple' => 0,
                            'allow_null' => 0,
                        ),
                        array(
                            'key' => 'field_64130c252e5bf',
                            'label' => 'متن خرید خانه',
                            'name' => 'buy_house',
                            'aria-label' => '',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 'دبی شهری با آب‌وهوای گرم و مرطوب است. در طول زمستان آب‌وهوای آن معتدل است و بیشتر روزهای سال آسمانی آفتابی دارد. جمعیت این شهر عمدتاً مسلمان هستند و زبان رسمی آن عربی و سپس انگلیسی است. آزادی‌های مدنی در این شهر برای تمام افراد تضمین شده است و امکانات بسیار مناسبی برای عموم کسانی که در این شهر اقامت دارند مهیا است. گفتنی است که بلندترین برج جهان یعنی برج خلیفه نیز در این شهر واقع است.',
                            'maxlength' => '',
                            'rows' => '',
                            'placeholder' => '',
                            'new_lines' => '',
                        ),
                        array(
                            'key' => 'field_64130c5616acb',
                            'label' => 'صفحه ی خرید خانه',
                            'name' => 'buy_house_url',
                            'aria-label' => '',
                            'type' => 'page_link',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'post_type' => array(
                                0 => 'page',
                            ),
                            'taxonomy' => '',
                            'allow_archives' => 1,
                            'multiple' => 0,
                            'allow_null' => 0,
                        ),
                        array(
                            'key' => 'field_64130c6c16acc',
                            'label' => 'متن اجاره ی خودرو در دبی',
                            'name' => 'rent_car',
                            'aria-label' => '',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 'اجارۀ خودرو در دبی علاوه بر راحتی فراوانی که برای شما به همراه می‌آورد، هزینه‌های شما را در زمان اقامت در دبی به صورت چشمگیری کاهش می‌دهد. هلدینگ ولکام دبی با فراهم کردن امکان اجارۀ خودروهای اقتصادی در دبی موجب شده است تمامی عزیزانی که از این سرویس استفاده می‌کنند آسایش بسیار زیادی را تجربه کنند. انواع ماشین‌های سواری را می‌توانید حتی پیش از ورود به دبی و از طریق دفتر ایران ما اجاره کنید و با خیالی راحت سفر خود را آغاز نمایید.',
                            'maxlength' => '',
                            'rows' => '',
                            'placeholder' => '',
                            'new_lines' => '',
                        ),
                        array(
                            'key' => 'field_64130c8216acd',
                            'label' => 'صفحه ی خرید خودرو',
                            'name' => 'rent_car_url',
                            'aria-label' => '',
                            'type' => 'page_link',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'post_type' => array(
                                0 => 'page',
                            ),
                            'taxonomy' => '',
                            'allow_archives' => 1,
                            'multiple' => 0,
                            'allow_null' => 0,
                        ),
                        array(
                            'key' => 'field_64130c9b16ace',
                            'label' => 'متن ثبت شرکت',
                            'name' => 'company',
                            'aria-label' => '',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 'دبی به دلیل داشتن وضعیت باثبات سیاسی و روند روبه‌رشد اقتصادی در سال‌های اخیر به یکی از مقاصد تجارتی از سراسر دنیا تبدیل شده است. افراد با ثبت شرکت در دبی می‌توانند اقامت امارات را برای خود و خانواده‌شان بگیرند. البته برای تأسیس شرکت نیازی نیست حتماً تابعۀ این کشور شد و بسیاری از تاجران ایرانی صرفاً برای رشد کسب‌وکار خود دست به این اقدام می‌زنند.',
                            'maxlength' => '',
                            'rows' => '',
                            'placeholder' => '',
                            'new_lines' => '',
                        ),
                        array(
                            'key' => 'field_64130cb416acf',
                            'label' => 'صفحه ی ثبت شرکت',
                            'name' => 'company_url',
                            'aria-label' => '',
                            'type' => 'page_link',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'post_type' => array(
                                0 => 'page',
                            ),
                            'taxonomy' => '',
                            'allow_archives' => 1,
                            'multiple' => 0,
                            'allow_null' => 0,
                        ),
                    ),
                    'location' => array(
                        array(
                            array(
                                'param' => 'page_template',
                                'operator' => '==',
                                'value' => 'index.php',
                            ),
                        ),
                    ),
                    'menu_order' => 0,
                    'position' => 'normal',
                    'style' => 'default',
                    'label_placement' => 'top',
                    'instruction_placement' => 'label',
                    'hide_on_screen' => '',
                    'active' => true,
                    'description' => '',
                    'show_in_rest' => 0,
                ));
                
                acf_add_local_field_group(array(
                    'key' => 'group_641310a8e38e4',
                    'title' => 'صفحه درباره ما',
                    'fields' => array(
                        array(
                            'key' => 'field_641310a9bb09c',
                            'label' => 'ایمیل',
                            'name' => 'email',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 'welcomedubai@Gmail.com',
                            'maxlength' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ),
                        array(
                            'key' => 'field_641310c5bb09d',
                            'label' => 'شماره تماس',
                            'name' => 'phone',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '+971 555 77 88 0',
                            'maxlength' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ),
                        array(
                            'key' => 'field_641310d9bb09e',
                            'label' => 'آدرس',
                            'name' => 'adr',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 'Box No. 261146 - Jebel Ali Free Zone - Dubai',
                            'maxlength' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ),
                        array(
                            'key' => 'field_641310e9bb09f',
                            'label' => 'اینستاگرام',
                            'name' => 'insta',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 'welcomedubai.ae',
                            'maxlength' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                        ),
                    ),
                    'location' => array(
                        array(
                            array(
                                'param' => 'page_template',
                                'operator' => '==',
                                'value' => 'about.php',
                            ),
                        ),
                    ),
                    'menu_order' => 0,
                    'position' => 'normal',
                    'style' => 'default',
                    'label_placement' => 'top',
                    'instruction_placement' => 'label',
                    'hide_on_screen' => '',
                    'active' => true,
                    'description' => '',
                    'show_in_rest' => 0,
                ));
                
                acf_add_local_field_group(array(
                    'key' => 'group_64131255b67b9',
                    'title' => 'ماشین های کرایه ای',
                    'fields' => array(
                        array(
                            'key' => 'field_6413125632149',
                            'label' => 'ماشین ها',
                            'name' => 'cars',
                            'aria-label' => '',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'block',
                            'pagination' => 0,
                            'min' => 0,
                            'max' => 0,
                            'collapsed' => '',
                            'button_label' => 'سطر جدید',
                            'rows_per_page' => 20,
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_641313293214a',
                                    'label' => 'تصاویر',
                                    'name' => 'pics',
                                    'aria-label' => '',
                                    'type' => 'gallery',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'return_format' => 'url',
                                    'library' => 'all',
                                    'min' => '',
                                    'max' => '',
                                    'min_width' => '',
                                    'min_height' => '',
                                    'min_size' => '',
                                    'max_width' => '',
                                    'max_height' => '',
                                    'max_size' => '',
                                    'mime_types' => '',
                                    'insert' => 'append',
                                    'preview_size' => 'medium',
                                    'parent_repeater' => 'field_6413125632149',
                                ),
                                array(
                                    'key' => 'field_6413159ba1e8b',
                                    'label' => 'نام خودرو',
                                    'name' => 'title',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'parent_repeater' => 'field_6413125632149',
                                ),
                                array(
                                    'key' => 'field_641313523214b',
                                    'label' => 'قیمت',
                                    'name' => 'price',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'parent_repeater' => 'field_6413125632149',
                                ),
                                array(
                                    'key' => 'field_6413135c3214c',
                                    'label' => 'امکانات',
                                    'name' => 'feau',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'parent_repeater' => 'field_6413125632149',
                                ),
                                array(
                                    'key' => 'field_6413136d3214d',
                                    'label' => 'سال تولید',
                                    'name' => 'year',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'parent_repeater' => 'field_6413125632149',
                                ),
                            ),
                        ),
                    ),
                    'location' => array(
                        array(
                            array(
                                'param' => 'page_template',
                                'operator' => '==',
                                'value' => 'car.php',
                            ),
                        ),
                    ),
                    'menu_order' => 0,
                    'position' => 'normal',
                    'style' => 'default',
                    'label_placement' => 'top',
                    'instruction_placement' => 'label',
                    'hide_on_screen' => '',
                    'active' => true,
                    'description' => '',
                    'show_in_rest' => 0,
                ));
                
                endif;		
?>